import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "mocha-bg": "var(--mocha-bg)",
        "mocha-bg-subtle": "var(--mocha-bg-subtle)",
        "mocha-card": "var(--mocha-card)",
        "nav-brown": "var(--nav-brown)",
        "nav-brown-border": "var(--nav-brown-border)",
        cream: "var(--cream)",
        "cream-soft": "var(--cream-soft)",
        "green-forest": "var(--green-forest)",
        "green-forest-hover": "var(--green-forest-hover)",
        "green-forest-band": "var(--green-forest-band)",
        "green-vibrant": "var(--green-vibrant)",
        "terracota-dark": "var(--terracota-dark)",
        "terracota-soft": "var(--terracota-soft)",
        "terracota-border": "var(--terracota-border)",
        "mocha-medium": "var(--mocha-medium)",
        "mocha-icon": "var(--mocha-icon)",
        "mocha-icon-hover": "var(--mocha-icon-hover)",
        "orange-burnt": "var(--orange-burnt)",
        "orange-burnt-hover": "var(--orange-burnt-hover)",
        "orange-focus": "var(--orange-focus)",
        "mocha-border": "var(--mocha-border)",
        "mocha-border-card": "var(--mocha-border-card)",
        "mocha-border-input": "var(--mocha-border-input)",
        "mocha-cell": "var(--mocha-cell)",
        "table-row-cream": "var(--table-row-cream)",
        "table-row-mocha": "var(--table-row-mocha)",
        "table-row-hover": "var(--table-row-hover)",
        "avatar-bg": "var(--avatar-bg)",
        "avatar-text": "var(--avatar-text)",
        danger: "var(--danger)",
        "danger-hover": "var(--danger-hover)",
      },
      boxShadow: {
        "card": "0 8px 32px rgba(61, 46, 38, 0.08)",
        "card-hover": "0 12px 40px rgba(61, 46, 38, 0.12)",
        "input-inner": "inset 0 1px 2px rgba(61, 46, 38, 0.06)",
        "btn-primary": "0 4px 14px rgba(196, 92, 42, 0.35)",
      },
    },
  },
  plugins: [],
} satisfies Config;
